name: BuildHostMakePyinstaller
on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'Tag'
        required: true
        default: ''
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: build with pyinstaller
      run: |
        python -m PyInstaller WindowsServerStart.py
    - uses: actions/upload-artifact@v2
      with:
        name: WindowsServerStart-artifact
        path: ./dist
    
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: WindowsServerStart-artifact

      - name: Zip file windows
        run: zip -r WindowsServerStart.zip ./WindowsServerStart

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tagname }}
          draft: false
          prerelease: false
          files: |
            WindowsServerStart.zip

